---
output: html_document
---
Project 1
========

The project for the first half of the semester is due on October 24th as a pull
request to this repository. The emphasis for this projet is on data analysis
using tools of reproducible research including version tracking, knitr, and R
markdown. You are free to answer any question you want, but you must provide a
quantitative report that utilizes the material we have covered durign the first
half of the semester.

***Ground rules...***
* Your document should layout your question in the introduction, provide a brief
synopsis for why it is important, describe how you obtained the data, your general
approach to analyzing the data, a summary of your results, a discussion, and
mention of what your future directions would be.
* You should post your project as a pull request to this repository as `*.Rmd`,
`*.md`, and `.html` files. Prior to submitting the files, you should set
`echo=FALSE` for all of the code chunks. This will hide the R code in the final
document.
* The final document should be approximately 5 pages when the code chunks are
hidden and  you use a normal sized font.
* I don't care what your question is or what subject domain it covers. The key is
that it needs to be data driven. Microbiology, video game statisitics, immunology,
whatever. Do something where it will be easy for you to come up with an interesting
question and fun analysis.

#Replicating Jhansi Leslie's Analysis for her Anaerobe 2014 Poster Entitled "Pre-Colonization By a Less Virulent Strain of *Clostridium difficile* Protects From Infection by a Lethal Strain" using R
###**By Shawn Whitefield**

##Introduction
##Methods
##Results
##Discussion

